@extends('layouts.business.blank')

@section('title')
    {{ __('E-Way Invoice') }}
@endsection

@section('main_content')
<div class="invoice-container">
    <div class="invoice-content p-4 bg-white">
        <!-- Print / PDF / Action Header -->
        <div class="row py-2 d-flex align-items-start justify-content-between border-bottom print-container d-print-none mb-3">
            <div class="col-md-6 d-flex align-items-center p-2">
                <span class="Money-Receipt fw-bold fs-4 text-primary">{{ __('E-Way Sales Invoice') }}</span>
            </div>
            <div class="col-md-6 d-flex justify-content-end align-items-center">
                <div class="d-flex gap-2 flex-wrap">
                    <a target="_blank" class="print-btn btn btn-danger d-flex align-items-center gap-1" 
                       href="{{ route('business.eway-bills.pdf', $eway_bill->id) }}">
                        <i class="far fa-file-pdf"></i> {{ __('PDF Download') }}
                    </a>
                    <button class="print-btn-2 print-btn btn btn-primary d-flex align-items-center gap-1" onclick="window.print()">
                        <i class="far fa-print"></i> {{ __('Print') }}
                    </button>
                    <a class="btn btn-secondary d-flex align-items-center gap-1" href="{{ route('business.eway-bills.index') }}">
                        <i class="far fa-arrow-left"></i> {{ __('Back') }}
                    </a>
                </div>
            </div>
        </div>

        <!-- Logo & Business details -->
        <div class="d-flex justify-content-between align-items-start gap-3 print-logo-container border-bottom pb-3 mb-3">
            <div class="d-flex align-items-center gap-2 logo pdf-logo">
                @if ((get_business_option('business-settings', $eway_bill->business_id)['show_a4_invoice_logo'] ?? 0) == 1)
                    <img class="invoice-logo" style="max-height: 70px;" src="{{ Storage::url(get_business_option('business-settings', $eway_bill->business_id)['a4_invoice_logo'] ?? 'assets/images/default.svg') }}">
                @else
                    <h3 class="fw-bold m-0 text-dark">{{ $eway_bill->business->companyName ?? '' }}</h3>
                @endif
            </div>
            <div class="text-end text-muted small">
                <p class="m-0 fw-bold text-dark">{{ $eway_bill->business->companyName ?? '' }}</p>
                <p class="m-0">{{ __('Address') }}: {{ $eway_bill->business->address ?? '' }}</p>
                <p class="m-0">{{ __('Mobile') }}: {{ $eway_bill->business->phoneNumber ?? '' }}</p>
                <p class="m-0">{{ __('Email') }}: {{ $eway_bill->business->email ?? '' }}</p>
                @if($eway_bill->business->vat_no)
                    <p class="m-0 fw-bold">{{ $eway_bill->business->vat_name ?: 'GSTIN' }}: {{ $eway_bill->business->vat_no }}</p>
                @endif
            </div>
        </div>

        <div class="text-center mb-3">
            <h4 class="text-uppercase fw-bold text-decoration-underline m-0">{{ __('E-Way Bill Invoice') }}</h4>
        </div>

        <!-- Transaction and Document info -->
        <div class="row mb-3 g-3">
            <div class="col-6">
                <table class="table table-sm table-borderless">
                    <tbody>
                        <tr>
                            <td class="fw-bold p-1 w-40">{{ __('Invoice Number') }}</td>
                            <td class="p-1">: {{ $eway_bill->invoice_number }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold p-1">{{ __('Invoice Date') }}</td>
                            <td class="p-1">: {{ formatted_date($eway_bill->invoice_date) }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold p-1">{{ __('Generated By') }}</td>
                            <td class="p-1">: {{ $eway_bill->user->name }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-6">
                <table class="table table-sm table-borderless">
                    <tbody>
                        <tr>
                            <td class="fw-bold p-1 w-40">{{ __('Supply Type') }}</td>
                            <td class="p-1">: {{ $eway_bill->supply_type }} - {{ $eway_bill->sub_type }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold p-1">{{ __('Document Type') }}</td>
                            <td class="p-1">: {{ $eway_bill->document_type }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Addresses block -->
        <div class="row mb-3 g-3">
            <!-- Dispatch From (Consignor) -->
            <div class="col-6">
                <div class="border p-2 rounded h-100 bg-light">
                    <h6 class="fw-bold border-bottom pb-1 mb-2 text-primary">{{ __('From (Consignor)') }}</h6>
                    <p class="m-0 fw-bold">{{ $eway_bill->from_name }}</p>
                    @if($eway_bill->from_gstin)
                        <p class="m-0 small">{{ __('GSTIN') }}: <strong>{{ $eway_bill->from_gstin }}</strong></p>
                    @endif
                    <p class="m-0 small">{{ __('Address') }}: {{ $eway_bill->from_address }}</p>
                    <p class="m-0 small">{{ __('PIN') }}: {{ $eway_bill->from_pincode }} | {{ __('State') }}: {{ $eway_bill->from_state }}</p>
                </div>
            </div>

            <!-- Delivery To (Consignee) -->
            <div class="col-6">
                <div class="border p-2 rounded h-100 bg-light">
                    <h6 class="fw-bold border-bottom pb-1 mb-2 text-primary">{{ __('To (Consignee)') }}</h6>
                    <p class="m-0 fw-bold">{{ $eway_bill->to_name }}</p>
                    @if($eway_bill->to_gstin)
                        <p class="m-0 small">{{ __('GSTIN') }}: <strong>{{ $eway_bill->to_gstin }}</strong></p>
                    @endif
                    <p class="m-0 small">{{ __('Address') }}: {{ $eway_bill->to_address }}</p>
                    <p class="m-0 small">{{ __('PIN') }}: {{ $eway_bill->to_pincode }} | {{ __('State') }}: {{ $eway_bill->to_state }}</p>
                </div>
            </div>
        </div>

        <!-- Transportation Parameters -->
        <div class="border rounded p-2 mb-3 bg-light">
            <h6 class="fw-bold border-bottom pb-1 mb-2 text-primary">{{ __('Transportation & Vehicle details') }}</h6>
            <div class="row g-2 small">
                <div class="col-4">
                    <strong>{{ __('Transporter') }}:</strong> {{ $eway_bill->transporter_name ?: __('N/A') }}
                </div>
                <div class="col-4">
                    <strong>{{ __('Transporter ID') }}:</strong> {{ $eway_bill->transporter_id ?: __('N/A') }}
                </div>
                <div class="col-4">
                    <strong>{{ __('Transport Mode') }}:</strong> {{ $eway_bill->transport_mode }}
                </div>
                <div class="col-4">
                    <strong>{{ __('Distance') }}:</strong> {{ $eway_bill->distance }} KM
                </div>
                <div class="col-4">
                    <strong>{{ __('Vehicle Number') }}:</strong> {{ $eway_bill->vehicle_number ?: __('N/A') }}
                </div>
                <div class="col-4">
                    <strong>{{ __('Vehicle Type') }}:</strong> {{ $eway_bill->vehicle_type }}
                </div>
            </div>
        </div>

        <!-- Items Details Table -->
        <div class="table-responsive mb-3">
            <table class="table table-bordered table-striped align-middle mb-0">
                <thead class="table-primary text-center">
                    <tr>
                        <th class="small py-1" style="width: 50px;">{{ __('SL') }}</th>
                        <th class="small py-1 text-start">{{ __('Item Description') }}</th>
                        <th class="small py-1">{{ __('HSN Code') }}</th>
                        <th class="small py-1">{{ __('Quantity') }}</th>
                        <th class="small py-1 text-end">{{ __('Unit Price') }}</th>
                        <th class="small py-1 text-end">{{ __('Discount') }}</th>
                        <th class="small py-1 text-end">{{ __('Tax Rate') }}</th>
                        <th class="small py-1 text-end">{{ __('Tax Amount') }}</th>
                        <th class="small py-1 text-end">{{ __('Total') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($eway_bill->details as $detail)
                        @php
                            $rowSubtotal = ($detail->price - $detail->discount) * $detail->quantity;
                        @endphp
                        <tr>
                            <td class="text-center py-1">{{ $loop->iteration }}</td>
                            <td class="py-1 text-start">
                                {{ $detail->product->productName ?? '' }}
                                @if($detail->stock && $detail->stock->batch_no)
                                    <span class="text-muted small">({{ __('Batch') }}: {{ $detail->stock->batch_no }})</span>
                                @endif
                            </td>
                            <td class="text-center py-1">{{ $detail->hsn_code ?: __('N/A') }}</td>
                            <td class="text-center py-1">{{ $detail->quantity }}</td>
                            <td class="text-end py-1">{{ currency_format($detail->price, currency: business_currency()) }}</td>
                            <td class="text-end py-1">{{ currency_format($detail->discount, currency: business_currency()) }}</td>
                            <td class="text-center py-1">{{ $detail->tax_percent }}%</td>
                            <td class="text-end py-1">{{ currency_format($detail->tax_amount, currency: business_currency()) }}</td>
                            <td class="text-end py-1">{{ currency_format($detail->total, currency: business_currency()) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Totals summary block -->
        <div class="row align-items-start justify-content-between mt-3">
            <div class="col-7">
                @if($eway_bill->notes)
                    <div class="border p-2 rounded bg-light small mb-2">
                        <strong>{{ __('Notes/Remarks') }}:</strong>
                        <p class="m-0">{{ $eway_bill->notes }}</p>
                    </div>
                @endif
                <h5 class="text-muted fw-bold text-uppercase fs-6 mt-2">{{ __('Amount in Words') }}:</h5>
                <h6 class="fw-bold fs-6 text-primary">{{ amountInWords($eway_bill->total_amount) }}</h6>
            </div>
            <div class="col-5">
                <table class="table table-sm table-bordered mb-0 small">
                    <tbody>
                        <tr>
                            <td class="fw-bold bg-light">{{ __('Subtotal') }}</td>
                            <td class="text-end">:</td>
                            <td class="text-end fw-bold">{{ currency_format($eway_bill->sub_total, currency: business_currency()) }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold bg-light">{{ __('Discount') }}</td>
                            <td class="text-end">:</td>
                            <td class="text-end text-danger">{{ currency_format($eway_bill->discount_amount, currency: business_currency()) }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold bg-light">{{ __('Taxes') }} ({{ __('GST/VAT') }})</td>
                            <td class="text-end">:</td>
                            <td class="text-end">{{ currency_format($eway_bill->tax_amount, currency: business_currency()) }}</td>
                        </tr>
                        <tr>
                            <td class="fw-bold bg-light">{{ __('Freight/Shipping') }}</td>
                            <td class="text-end">:</td>
                            <td class="text-end">{{ currency_format($eway_bill->shipping_charge, currency: business_currency()) }}</td>
                        </tr>
                        <tr class="table-primary fw-bold">
                            <td class="text-uppercase">{{ __('Total Invoice Value') }}</td>
                            <td class="text-end">:</td>
                            <td class="text-end">{{ currency_format($eway_bill->total_amount, currency: business_currency()) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Signature lines -->
        <div class="row mt-5 pt-4">
            <div class="col-6 text-center">
                <div style="border-top: 1px solid #dee2e6; width: 60%; margin: 0 auto;" class="pt-2">
                    <p class="fw-bold mb-0 small text-dark">{{ __('Customer Signature') }}</p>
                </div>
            </div>
            <div class="col-6 text-center">
                <div style="border-top: 1px solid #dee2e6; width: 60%; margin: 0 auto;" class="pt-2">
                    <p class="fw-bold mb-0 small text-dark">{{ __('Authorized Signature') }}</p>
                    <p class="text-muted small mb-0">{{ $eway_bill->business->companyName }}</p>
                </div>
            </div>
        </div>

        <!-- Footer credit text -->
        <div class="text-center text-muted small mt-5 pt-3 border-top">
            <p class="m-0">{{ get_option('general')['admin_footer_text'] ?? '' }} : {{ get_option('general')['admin_footer_link_text'] ?? '' }}</p>
        </div>
    </div>
</div>
@endsection
